## PvP-Invite System by SlimeLab MC Server

    messages:
      # Placeholder %player%
      Need_Invite: "&6請先使用蹲下+左鍵發送對決邀請!"
      Wait_for_Accept: "&6已寄送邀請給 &b%player% &6正在等待他的回覆"
      Invite: "&b%player% &6邀請你進行決鬥 使用蹲下+左鍵他接受對決邀請!"
      Invite_OverTime: "&6邀請逾時,請重新邀請"
      Accept: "&6你同意了 &b%player% &6的決鬥邀請"
      Deny: "&6你拒絕了 &b%player% &6的決鬥邀請"
      AcceptTo: "&b%player% &6同意了你的決鬥邀請"
      DenyTo: "&b%player% &6拒絕了你的決鬥邀請"
      ChooseAccept: " &a[同意] "
      ChooseDeny: " &c[拒絕] "
      ChooseCommand: "/pvp Accept %player%,/pvp Deny %player%"
      PVPStart: "&6決鬥將在%time%秒後開始!!!"
      PVPEnd: "&6決鬥結束,獲勝者 &b%player%"
      Command_Permission: "這個指令只能由玩家使用"
      Target_Offline: "目標玩家&b%player%不在線上!"
      Command: "&c指令使用方法: /pvp [Invite|Accept|Deny] [player]"