name: PvPInvite
version: 1.0
main: me.slimelab.PvPInvite
api-version: 1.14
authors: [coco0325, jdibw]
commands:
  pvp:
    description: PVP command.
    usage: /pvp [Invite|Accept|Deny] [player]

permissions:
  PvPInvite.pvp:
    description: This is a pvp command.
    default: true
  PvPInvite.*:
    description: Wildcard permission
    default: op
    children:
      PvPInvite.pvp: true